//! DigestDigest trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::DigestDigest;

pub type DigestDigestTriggerEvent      = TriggerEvent;
pub type DigestDigestTriggerContext    = TriggerContext<DigestDigest>;
pub type DigestDigestTriggerContextMut = TriggerContextMut<DigestDigest>;
pub type DigestDigestActionExecutor    = ActionExecutor;
pub type DigestDigestTriggerRegistry   = TriggerRegistry<DigestDigest>;
pub type DigestDigestTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<DigestDigest>, TriggerEvent>;

// State machine trigger handlers

/// Create a default registry pre-populated with all handlers for DigestDigest.
pub fn digest_digest_trigger_registry() -> DigestDigestTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
