//! DigestSubscription trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::DigestSubscription;

pub type DigestSubscriptionTriggerEvent      = TriggerEvent;
pub type DigestSubscriptionTriggerContext    = TriggerContext<DigestSubscription>;
pub type DigestSubscriptionTriggerContextMut = TriggerContextMut<DigestSubscription>;
pub type DigestSubscriptionActionExecutor    = ActionExecutor;
pub type DigestSubscriptionTriggerRegistry   = TriggerRegistry<DigestSubscription>;
pub type DigestSubscriptionTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<DigestSubscription>, TriggerEvent>;

// State machine trigger handlers

/// Create a default registry pre-populated with all handlers for DigestSubscription.
pub fn digest_subscription_trigger_registry() -> DigestSubscriptionTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
