//! State machine for digest_state workflow
//!
//! Generated by metaphor-schema

use serde::{Deserialize, Serialize};
use std::str::FromStr;

/// States for digest_state workflow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum digest_stateState {
    /// Initial state
    Activated,
    /// Final state
    Deactivated,
}

impl Default for digest_stateState {
    fn default() -> Self {
        Self::Activated
    }
}

impl std::fmt::Display for digest_stateState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Activated => write!(f, "activated"),
            Self::Deactivated => write!(f, "deactivated"),
        }
    }
}

impl FromStr for digest_stateState {
    type Err = StateMachineError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "activated" => Ok(Self::Activated),
            "deactivated" => Ok(Self::Deactivated),
            _ => Err(StateMachineError::InvalidState(s.to_string())),
        }
    }
}

impl digest_stateState {
    /// Check if this is the initial state
    pub fn is_initial(&self) -> bool {
        matches!(self, Self::Activated)
    }

    /// Check if this is a final state
    pub fn is_final(&self) -> bool {
        matches!(self, Self::Deactivated)
    }

    /// Get all possible states
    pub fn all() -> Vec<Self> {
        vec![
            Self::Activated,
            Self::Deactivated,
        ]
    }
}

/// Transitions for digest_state workflow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum digest_stateTransition {
    /// * -> activated
    ActionActivate,
    /// * -> deactivated
    ActionDeactivate,
}

impl std::fmt::Display for digest_stateTransition {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ActionActivate => write!(f, "action_activate"),
            Self::ActionDeactivate => write!(f, "action_deactivate"),
        }
    }
}

impl FromStr for digest_stateTransition {
    type Err = StateMachineError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "action_activate" => Ok(Self::ActionActivate),
            "action_deactivate" => Ok(Self::ActionDeactivate),
            _ => Err(StateMachineError::InvalidTransition(s.to_string())),
        }
    }
}

impl digest_stateTransition {
    /// Get the target state of this transition
    pub fn target_state(&self) -> digest_stateState {
        match self {
            Self::ActionActivate => digest_stateState::Activated,
            Self::ActionDeactivate => digest_stateState::Deactivated,
        }
    }

    /// Get all transitions
    pub fn all() -> Vec<Self> {
        vec![
            Self::ActionActivate,
            Self::ActionDeactivate,
        ]
    }

    /// Get allowed roles for this transition
    pub fn allowed_roles(&self) -> &'static [&'static str] {
        match self {
            Self::ActionActivate => &[],
            Self::ActionDeactivate => &[],
        }
    }
}

use super::StateMachineError;

/// State machine for digest_state workflow
#[derive(Debug, Clone)]
pub struct digest_stateStateMachine {
    current_state: digest_stateState,
}

impl digest_stateStateMachine {
    /// Create a new state machine with initial state
    pub fn new() -> Self {
        Self {
            current_state: digest_stateState::default(),
        }
    }

    /// Create from an existing state
    pub fn from_state(state: digest_stateState) -> Self {
        Self { current_state: state }
    }

    /// Get the current state
    pub fn current_state(&self) -> digest_stateState {
        self.current_state
    }

    /// Check if a transition is allowed from the current state
    pub fn can_transition(&self, transition: digest_stateTransition) -> bool {
        if matches!(self.current_state, digest_stateState::Deactivated) {
            return false;
        }

        match (self.current_state, transition) {
            (_, digest_stateTransition::ActionActivate) => true,
            (_, digest_stateTransition::ActionDeactivate) => true,
            _ => false,
        }
    }

    /// Check if a transition is allowed for a given role
    pub fn can_transition_with_role(&self, transition: digest_stateTransition, role: &str) -> bool {
        if !self.can_transition(transition) {
            return false;
        }

        let allowed_roles = transition.allowed_roles();
        if allowed_roles.is_empty() {
            return true; // No role restriction
        }

        allowed_roles.iter().any(|r| *r == role || *r == "*")
    }

    /// Apply a transition, returning the new state
    pub fn transition(&mut self, transition: digest_stateTransition) -> Result<digest_stateState, StateMachineError> {
        if !self.can_transition(transition) {
            return Err(StateMachineError::TransitionNotAllowed {
                transition: transition.to_string(),
                from: self.current_state.to_string(),
            });
        }

        self.current_state = transition.target_state();
        Ok(self.current_state)
    }

    /// Apply a transition with role check
    pub fn transition_with_role(&mut self, transition: digest_stateTransition, role: &str) -> Result<digest_stateState, StateMachineError> {
        // Check basic transition validity first
        if !self.can_transition(transition) {
            return Err(StateMachineError::TransitionNotAllowed {
                transition: transition.to_string(),
                from: self.current_state.to_string(),
            });
        }

        // Check role authorization
        if !self.can_transition_with_role(transition, role) {
            return Err(StateMachineError::RoleNotAuthorized {
                role: role.to_string(),
                transition: transition.to_string(),
            });
        }

        self.current_state = transition.target_state();
        Ok(self.current_state)
    }

    /// Get all available transitions from the current state
    pub fn available_transitions(&self) -> Vec<digest_stateTransition> {
        digest_stateTransition::all()
            .into_iter()
            .filter(|t| self.can_transition(*t))
            .collect()
    }

    /// Get all available transitions for a given role
    pub fn available_transitions_for_role(&self, role: &str) -> Vec<digest_stateTransition> {
        digest_stateTransition::all()
            .into_iter()
            .filter(|t| self.can_transition_with_role(*t, role))
            .collect()
    }

    /// Attempt to transition directly to a target state.
    ///
    /// Finds any transition that leads to the target state and applies it.
    /// Returns Err if no valid transition leads from current state to target.
    pub fn transition_to_state(&mut self, target: digest_stateState) -> Result<digest_stateState, StateMachineError> {
        let valid = digest_stateTransition::all().into_iter()
            .filter(|t| self.can_transition(*t))
            .find(|t| t.target_state() == target);
        match valid {
            Some(t) => self.transition(t),
            None => Err(StateMachineError::TransitionNotAllowed {
                transition: target.to_string(),
                from: self.current_state.to_string(),
            }),
        }
    }
}

impl Default for digest_stateStateMachine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_initial_state() {
        let sm = digest_stateStateMachine::new();
        assert_eq!(sm.current_state(), digest_stateState::Activated);
        assert!(sm.current_state().is_initial());
    }

    #[test]
    fn test_valid_transition() {
        let mut sm = digest_stateStateMachine::new();
        assert!(sm.can_transition(digest_stateTransition::ActionActivate));
        let result = sm.transition(digest_stateTransition::ActionActivate);
        assert!(result.is_ok());
        assert_eq!(sm.current_state(), digest_stateState::Activated);
    }

    #[test]
    fn test_invalid_transition() {
        // All transitions are valid from all states (wildcard), test passes
        assert!(true);
    }

    #[test]
    fn test_state_parsing() {
        let state: digest_stateState = "activated".parse().unwrap();
        assert_eq!(state, digest_stateState::Activated);
    }

    #[test]
    fn test_available_transitions() {
        let sm = digest_stateStateMachine::new();
        let available = sm.available_transitions();
        // Should have at least some transitions available from initial state
        assert!(!available.is_empty() || sm.current_state().is_final());
    }
}
