//! State machine for DigestSubscriptionState workflow
//!
//! Generated by metaphor-schema

use serde::{Deserialize, Serialize};
use std::str::FromStr;

/// States for DigestSubscriptionState workflow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DigestSubscriptionStateState {
    /// Initial state
    Subscribed,
    /// Final state
    Unsubscribed,
}

impl Default for DigestSubscriptionStateState {
    fn default() -> Self {
        Self::Subscribed
    }
}

impl std::fmt::Display for DigestSubscriptionStateState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Subscribed => write!(f, "subscribed"),
            Self::Unsubscribed => write!(f, "unsubscribed"),
        }
    }
}

impl FromStr for DigestSubscriptionStateState {
    type Err = StateMachineError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "subscribed" => Ok(Self::Subscribed),
            "unsubscribed" => Ok(Self::Unsubscribed),
            _ => Err(StateMachineError::InvalidState(s.to_string())),
        }
    }
}

impl DigestSubscriptionStateState {
    /// Check if this is the initial state
    pub fn is_initial(&self) -> bool {
        matches!(self, Self::Subscribed)
    }

    /// Check if this is a final state
    pub fn is_final(&self) -> bool {
        matches!(self, Self::Unsubscribed)
    }

    /// Get all possible states
    pub fn all() -> Vec<Self> {
        vec![
            Self::Subscribed,
            Self::Unsubscribed,
        ]
    }
}

/// Transitions for DigestSubscriptionState workflow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DigestSubscriptionStateTransition {
    /// subscribed -> unsubscribed
    Unsubscribe,
    /// unsubscribed -> subscribed
    Resubscribe,
}

impl std::fmt::Display for DigestSubscriptionStateTransition {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unsubscribe => write!(f, "unsubscribe"),
            Self::Resubscribe => write!(f, "resubscribe"),
        }
    }
}

impl FromStr for DigestSubscriptionStateTransition {
    type Err = StateMachineError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "unsubscribe" => Ok(Self::Unsubscribe),
            "resubscribe" => Ok(Self::Resubscribe),
            _ => Err(StateMachineError::InvalidTransition(s.to_string())),
        }
    }
}

impl DigestSubscriptionStateTransition {
    /// Get the target state of this transition
    pub fn target_state(&self) -> DigestSubscriptionStateState {
        match self {
            Self::Unsubscribe => DigestSubscriptionStateState::Unsubscribed,
            Self::Resubscribe => DigestSubscriptionStateState::Subscribed,
        }
    }

    /// Get all transitions
    pub fn all() -> Vec<Self> {
        vec![
            Self::Unsubscribe,
            Self::Resubscribe,
        ]
    }

    /// Get allowed roles for this transition
    pub fn allowed_roles(&self) -> &'static [&'static str] {
        match self {
            Self::Unsubscribe => &[],
            Self::Resubscribe => &[],
        }
    }
}

use super::StateMachineError;

/// State machine for DigestSubscriptionState workflow
#[derive(Debug, Clone)]
pub struct DigestSubscriptionStateStateMachine {
    current_state: DigestSubscriptionStateState,
}

impl DigestSubscriptionStateStateMachine {
    /// Create a new state machine with initial state
    pub fn new() -> Self {
        Self {
            current_state: DigestSubscriptionStateState::default(),
        }
    }

    /// Create from an existing state
    pub fn from_state(state: DigestSubscriptionStateState) -> Self {
        Self { current_state: state }
    }

    /// Get the current state
    pub fn current_state(&self) -> DigestSubscriptionStateState {
        self.current_state
    }

    /// Check if a transition is allowed from the current state
    pub fn can_transition(&self, transition: DigestSubscriptionStateTransition) -> bool {
        match (self.current_state, transition) {
            (DigestSubscriptionStateState::Subscribed, DigestSubscriptionStateTransition::Unsubscribe) => true,
            (DigestSubscriptionStateState::Unsubscribed, DigestSubscriptionStateTransition::Resubscribe) => true,
            _ => false,
        }
    }

    /// Check if a transition is allowed for a given role
    pub fn can_transition_with_role(&self, transition: DigestSubscriptionStateTransition, role: &str) -> bool {
        if !self.can_transition(transition) {
            return false;
        }

        let allowed_roles = transition.allowed_roles();
        if allowed_roles.is_empty() {
            return true; // No role restriction
        }

        allowed_roles.iter().any(|r| *r == role || *r == "*")
    }

    /// Apply a transition, returning the new state
    pub fn transition(&mut self, transition: DigestSubscriptionStateTransition) -> Result<DigestSubscriptionStateState, StateMachineError> {
        if !self.can_transition(transition) {
            return Err(StateMachineError::TransitionNotAllowed {
                transition: transition.to_string(),
                from: self.current_state.to_string(),
            });
        }

        self.current_state = transition.target_state();
        Ok(self.current_state)
    }

    /// Apply a transition with role check
    pub fn transition_with_role(&mut self, transition: DigestSubscriptionStateTransition, role: &str) -> Result<DigestSubscriptionStateState, StateMachineError> {
        // Check basic transition validity first
        if !self.can_transition(transition) {
            return Err(StateMachineError::TransitionNotAllowed {
                transition: transition.to_string(),
                from: self.current_state.to_string(),
            });
        }

        // Check role authorization
        if !self.can_transition_with_role(transition, role) {
            return Err(StateMachineError::RoleNotAuthorized {
                role: role.to_string(),
                transition: transition.to_string(),
            });
        }

        self.current_state = transition.target_state();
        Ok(self.current_state)
    }

    /// Get all available transitions from the current state
    pub fn available_transitions(&self) -> Vec<DigestSubscriptionStateTransition> {
        DigestSubscriptionStateTransition::all()
            .into_iter()
            .filter(|t| self.can_transition(*t))
            .collect()
    }

    /// Get all available transitions for a given role
    pub fn available_transitions_for_role(&self, role: &str) -> Vec<DigestSubscriptionStateTransition> {
        DigestSubscriptionStateTransition::all()
            .into_iter()
            .filter(|t| self.can_transition_with_role(*t, role))
            .collect()
    }

    /// Attempt to transition directly to a target state.
    ///
    /// Finds any transition that leads to the target state and applies it.
    /// Returns Err if no valid transition leads from current state to target.
    pub fn transition_to_state(&mut self, target: DigestSubscriptionStateState) -> Result<DigestSubscriptionStateState, StateMachineError> {
        let valid = DigestSubscriptionStateTransition::all().into_iter()
            .filter(|t| self.can_transition(*t))
            .find(|t| t.target_state() == target);
        match valid {
            Some(t) => self.transition(t),
            None => Err(StateMachineError::TransitionNotAllowed {
                transition: target.to_string(),
                from: self.current_state.to_string(),
            }),
        }
    }
}

impl Default for DigestSubscriptionStateStateMachine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_initial_state() {
        let sm = DigestSubscriptionStateStateMachine::new();
        assert_eq!(sm.current_state(), DigestSubscriptionStateState::Subscribed);
        assert!(sm.current_state().is_initial());
    }

    #[test]
    fn test_valid_transition() {
        let mut sm = DigestSubscriptionStateStateMachine::from_state(DigestSubscriptionStateState::Subscribed);
        assert!(sm.can_transition(DigestSubscriptionStateTransition::Unsubscribe));
        let result = sm.transition(DigestSubscriptionStateTransition::Unsubscribe);
        assert!(result.is_ok());
        assert_eq!(sm.current_state(), DigestSubscriptionStateState::Unsubscribed);
    }

    #[test]
    fn test_invalid_transition() {
        let mut sm = DigestSubscriptionStateStateMachine::from_state(DigestSubscriptionStateState::Subscribed);
        // Resubscribe is not valid from Subscribed state
        let result = sm.transition(DigestSubscriptionStateTransition::Resubscribe);
        assert!(result.is_err());
    }

    #[test]
    fn test_state_parsing() {
        let state: DigestSubscriptionStateState = "subscribed".parse().unwrap();
        assert_eq!(state, DigestSubscriptionStateState::Subscribed);
    }

    #[test]
    fn test_available_transitions() {
        let sm = DigestSubscriptionStateStateMachine::new();
        let available = sm.available_transitions();
        // Should have at least some transitions available from initial state
        assert!(!available.is_empty() || sm.current_state().is_final());
    }
}
