//! DigestTip DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::DigestTip;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new DigestTip
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateDigestTipDto {
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "tip_description")]
    pub tip_description: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "group_key")]
    pub group_key: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a DigestTip
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateDigestTipDto {
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "tip_description")]
    pub tip_description: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "group_key")]
    pub group_key: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a DigestTip
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchDigestTipDto {
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "tip_description")]
    pub tip_description: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "group_key")]
    pub group_key: Option<String>,
}

impl PatchDigestTipDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.sequence.is_some() || self.name.is_some() || self.tip_description.is_some() || self.group_key.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for DigestTip entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DigestTipResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub tip_description: String,
    pub group_key: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for DigestTip entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DigestTipListResponseDto {
    /// List of items
    pub items: Vec<DigestTipResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl DigestTipListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<DigestTipResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DigestTipSummaryDto {
    pub id: Uuid,
    pub sequence: i32,
    pub name: String,
    pub tip_description: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<DigestTip> for DigestTipResponseDto {
    fn from(entity: DigestTip) -> Self {
        Self {
            id: entity.id,
            sequence: entity.sequence,
            name: entity.name,
            tip_description: entity.tip_description,
            group_key: entity.group_key,
            metadata: entity.metadata,
        }
    }
}

impl From<DigestTip> for DigestTipSummaryDto {
    fn from(entity: DigestTip) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            sequence: entity.sequence,
            name: entity.name,
            tip_description: entity.tip_description,
            created_at,
        }
    }
}

impl From<CreateDigestTipDto> for DigestTip {
    fn from(dto: CreateDigestTipDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            sequence: dto.sequence,
            name: dto.name,
            tip_description: dto.tip_description,
            group_key: dto.group_key,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&DigestTip> for DigestTipResponseDto {
    fn from(entity: &DigestTip) -> Self {
        Self {
            id: entity.id.clone(),
            sequence: entity.sequence.clone(),
            name: entity.name.clone(),
            tip_description: entity.tip_description.clone(),
            group_key: entity.group_key.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateDigestTipDto> for DigestTip {
    fn from_create_dto(dto: CreateDigestTipDto) -> backbone_core::ServiceResult<Self> {
        Ok(DigestTip::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateDigestTipDto> for DigestTip {
    fn apply_update(mut self, dto: UpdateDigestTipDto) -> backbone_core::ServiceResult<Self> {
        self.sequence = dto.sequence;
        self.name = dto.name;
        self.tip_description = dto.tip_description;
        self.group_key = dto.group_key;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to DigestTip here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
