//! DigestDigestKpi DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::DigestDigestKpi;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new DigestDigestKpi
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateDigestDigestKpiDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "digest_id")]
    pub digest_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "kpi_key")]
    pub kpi_key: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a DigestDigestKpi
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateDigestDigestKpiDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "digest_id")]
    pub digest_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "kpi_key")]
    pub kpi_key: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a DigestDigestKpi
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchDigestDigestKpiDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "digest_id")]
    pub digest_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "kpi_key")]
    pub kpi_key: Option<String>,
}

impl PatchDigestDigestKpiDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.digest_id.is_some() || self.kpi_key.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for DigestDigestKpi entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DigestDigestKpiResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub digest_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub kpi_key: String,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for DigestDigestKpi entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DigestDigestKpiListResponseDto {
    /// List of items
    pub items: Vec<DigestDigestKpiResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl DigestDigestKpiListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<DigestDigestKpiResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DigestDigestKpiSummaryDto {
    pub id: Uuid,
    pub digest_id: Uuid,
    pub kpi_key: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<DigestDigestKpi> for DigestDigestKpiResponseDto {
    fn from(entity: DigestDigestKpi) -> Self {
        Self {
            id: entity.id,
            digest_id: entity.digest_id,
            kpi_key: entity.kpi_key,
            metadata: entity.metadata,
        }
    }
}

impl From<DigestDigestKpi> for DigestDigestKpiSummaryDto {
    fn from(entity: DigestDigestKpi) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            digest_id: entity.digest_id,
            kpi_key: entity.kpi_key,
            created_at,
        }
    }
}

impl From<CreateDigestDigestKpiDto> for DigestDigestKpi {
    fn from(dto: CreateDigestDigestKpiDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            digest_id: dto.digest_id,
            kpi_key: dto.kpi_key,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&DigestDigestKpi> for DigestDigestKpiResponseDto {
    fn from(entity: &DigestDigestKpi) -> Self {
        Self {
            id: entity.id.clone(),
            digest_id: entity.digest_id.clone(),
            kpi_key: entity.kpi_key.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateDigestDigestKpiDto> for DigestDigestKpi {
    fn from_create_dto(dto: CreateDigestDigestKpiDto) -> backbone_core::ServiceResult<Self> {
        Ok(DigestDigestKpi::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateDigestDigestKpiDto> for DigestDigestKpi {
    fn apply_update(mut self, dto: UpdateDigestDigestKpiDto) -> backbone_core::ServiceResult<Self> {
        self.digest_id = dto.digest_id;
        self.kpi_key = dto.kpi_key;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to DigestDigestKpi here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
