//! DigestDigest DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::DigestDigest;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::DigestPeriodicity;
use crate::domain::entity::DigestState;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new DigestDigest
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateDigestDigestDto {
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub periodicity: DigestPeriodicity,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "next_run_date")]
    pub next_run_date: Option<NaiveDate>,
    pub state: DigestState,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a DigestDigest
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateDigestDigestDto {
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub periodicity: DigestPeriodicity,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "next_run_date")]
    pub next_run_date: Option<NaiveDate>,
    pub state: DigestState,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a DigestDigest
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchDigestDigestDto {
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub periodicity: Option<DigestPeriodicity>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "next_run_date")]
    pub next_run_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<DigestState>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
}

impl PatchDigestDigestDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.periodicity.is_some() || self.next_run_date.is_some() || self.state.is_some() || self.company_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for DigestDigest entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DigestDigestResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub periodicity: DigestPeriodicity,
    pub next_run_date: Option<NaiveDate>,
    pub state: DigestState,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for DigestDigest entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DigestDigestListResponseDto {
    /// List of items
    pub items: Vec<DigestDigestResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl DigestDigestListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<DigestDigestResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DigestDigestSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub periodicity: DigestPeriodicity,
    pub next_run_date: Option<NaiveDate>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<DigestDigest> for DigestDigestResponseDto {
    fn from(entity: DigestDigest) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            periodicity: entity.periodicity,
            next_run_date: entity.next_run_date,
            state: entity.state,
            company_id: entity.company_id,
            metadata: entity.metadata,
        }
    }
}

impl From<DigestDigest> for DigestDigestSummaryDto {
    fn from(entity: DigestDigest) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            periodicity: entity.periodicity,
            next_run_date: entity.next_run_date,
            created_at,
        }
    }
}

impl From<CreateDigestDigestDto> for DigestDigest {
    fn from(dto: CreateDigestDigestDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            periodicity: dto.periodicity,
            next_run_date: dto.next_run_date,
            state: dto.state,
            company_id: dto.company_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&DigestDigest> for DigestDigestResponseDto {
    fn from(entity: &DigestDigest) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            periodicity: entity.periodicity.clone(),
            next_run_date: entity.next_run_date.clone(),
            state: entity.state.clone(),
            company_id: entity.company_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateDigestDigestDto> for DigestDigest {
    fn from_create_dto(dto: CreateDigestDigestDto) -> backbone_core::ServiceResult<Self> {
        Ok(DigestDigest::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateDigestDigestDto> for DigestDigest {
    fn apply_update(mut self, dto: UpdateDigestDigestDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.periodicity = dto.periodicity;
        self.next_run_date = dto.next_run_date;
        self.state = dto.state;
        self.company_id = dto.company_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to DigestDigest here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
