//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod digest_digest_specification;
pub mod digest_subscription_specification;
pub mod digest_digest_kpi_specification;
pub mod digest_tip_specification;
pub mod digest_tip_user_specification;

// <<< CUSTOM
// END CUSTOM
