//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod digest_digest_domain_policy;
pub mod digest_subscription_domain_policy;
pub mod digest_digest_kpi_domain_policy;
pub mod digest_tip_domain_policy;
pub mod digest_tip_user_domain_policy;

pub use digest_digest_domain_policy::DigestDigestDomainPolicy;
pub use digest_subscription_domain_policy::DigestSubscriptionDomainPolicy;
pub use digest_digest_kpi_domain_policy::DigestDigestKpiDomainPolicy;
pub use digest_tip_domain_policy::DigestTipDomainPolicy;
pub use digest_tip_user_domain_policy::DigestTipUserDomainPolicy;

// <<< CUSTOM
// END CUSTOM
