//! Application service for DigestDigest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `digest_digest_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDigestDigestDto, UpdateDigestDigestDto};
use crate::domain::entity::DigestDigest;
use crate::infrastructure::persistence::DigestDigestRepository;

/// Application service for DigestDigest entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `digest_digest_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DigestDigestServiceCustom {
///     inner: Arc<DigestDigestService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DigestDigestService = GenericCrudService<
    DigestDigest,
    CreateDigestDigestDto,
    UpdateDigestDigestDto,
    DigestDigestRepository,
>;

// <<< CUSTOM
// END CUSTOM
