//! Application service for DigestDigestKpi entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `digest_digest_kpi_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDigestDigestKpiDto, UpdateDigestDigestKpiDto};
use crate::domain::entity::DigestDigestKpi;
use crate::infrastructure::persistence::DigestDigestKpiRepository;

/// Application service for DigestDigestKpi entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `digest_digest_kpi_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DigestDigestKpiServiceCustom {
///     inner: Arc<DigestDigestKpiService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DigestDigestKpiService = GenericCrudService<
    DigestDigestKpi,
    CreateDigestDigestKpiDto,
    UpdateDigestDigestKpiDto,
    DigestDigestKpiRepository,
>;

// <<< CUSTOM
// END CUSTOM
