//! Application service for DigestTip entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `digest_tip_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDigestTipDto, UpdateDigestTipDto};
use crate::domain::entity::DigestTip;
use crate::infrastructure::persistence::DigestTipRepository;

/// Application service for DigestTip entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `digest_tip_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DigestTipServiceCustom {
///     inner: Arc<DigestTipService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DigestTipService = GenericCrudService<
    DigestTip,
    CreateDigestTipDto,
    UpdateDigestTipDto,
    DigestTipRepository,
>;

// <<< CUSTOM
// END CUSTOM
