//! Application service for DigestTipUser entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `digest_tip_user_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDigestTipUserDto, UpdateDigestTipUserDto};
use crate::domain::entity::DigestTipUser;
use crate::infrastructure::persistence::DigestTipUserRepository;

/// Application service for DigestTipUser entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `digest_tip_user_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DigestTipUserServiceCustom {
///     inner: Arc<DigestTipUserService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DigestTipUserService = GenericCrudService<
    DigestTipUser,
    CreateDigestTipUserDto,
    UpdateDigestTipUserDto,
    DigestTipUserRepository,
>;

// <<< CUSTOM
// END CUSTOM
