-- DigestTipUser Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the digest.digest_tip_users table.
-- Customize this file to add your initial data.

-- INSERT INTO digest.digest_tip_users (
--     id,
--     tip_id,
--     user_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO digest.digest_tip_users (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

