-- Migration: Create digest_digests table
-- Generated by metaphor-schema

-- Create digest_periodicity enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'digest_periodicity') THEN
        CREATE TYPE digest_periodicity AS ENUM ('daily', 'weekly', 'monthly', 'quarterly');
    END IF;
END
$$;

-- Create digest_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'digest_state') THEN
        CREATE TYPE digest_state AS ENUM ('activated', 'deactivated');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS digest;

CREATE TABLE IF NOT EXISTS digest.digest_digests (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    periodicity digest_periodicity NOT NULL DEFAULT 'daily',
    next_run_date DATE,
    state digest_state NOT NULL DEFAULT 'activated',
    company_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_digest_digests_company_id ON digest.digest_digests (company_id);

CREATE INDEX IF NOT EXISTS idx_digest_digests_state_next_run_date ON digest.digest_digests (state, next_run_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_digest_digests_metadata_gin ON digest.digest_digests USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_digest_digests_metadata_deleted_at ON digest.digest_digests ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_digest_digests_metadata_created_at ON digest.digest_digests ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_digest_digests_metadata_updated_at ON digest.digest_digests ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION digest.digest_digests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS digest_digests_insert_audit ON digest.digest_digests;
CREATE TRIGGER digest_digests_insert_audit BEFORE INSERT ON digest.digest_digests
    FOR EACH ROW EXECUTE FUNCTION digest.digest_digests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS digest_digests_update_audit ON digest.digest_digests;
CREATE TRIGGER digest_digests_update_audit BEFORE UPDATE ON digest.digest_digests
    FOR EACH ROW EXECUTE FUNCTION digest.digest_digests_audit_timestamp();
