-- Company RLS fence for digest module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for digest.digest_digests
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE digest.digest_digests ENABLE ROW LEVEL SECURITY;
ALTER TABLE digest.digest_digests FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS digest_digests_company_isolation ON digest.digest_digests;
CREATE POLICY digest_digests_company_isolation ON digest.digest_digests
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

