-- Enum types for digest module
-- Generated by metaphor-schema

-- Create digest_periodicity enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'digest_periodicity') THEN
        CREATE TYPE digest_periodicity AS ENUM ('daily', 'weekly', 'monthly', 'quarterly');
    END IF;
END
$$;

-- Create digest_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'digest_state') THEN
        CREATE TYPE digest_state AS ENUM ('activated', 'deactivated');
    END IF;
END
$$;

-- Create digest_subscription_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'digest_subscription_state') THEN
        CREATE TYPE digest_subscription_state AS ENUM ('subscribed', 'unsubscribed');
    END IF;
END
$$;

