-- Audit Triggers Migration for digest module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: DigestDigest (digest.digest_digests)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION digest.digest_digests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS digest_digests_insert_audit ON digest.digest_digests;
CREATE TRIGGER digest_digests_insert_audit BEFORE INSERT ON digest.digest_digests
    FOR EACH ROW EXECUTE FUNCTION digest.digest_digests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS digest_digests_update_audit ON digest.digest_digests;
CREATE TRIGGER digest_digests_update_audit BEFORE UPDATE ON digest.digest_digests
    FOR EACH ROW EXECUTE FUNCTION digest.digest_digests_audit_timestamp();

-- ==============================================================================
-- Table: DigestSubscription (digest.digest_subscriptions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION digest.digest_subscriptions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS digest_subscriptions_insert_audit ON digest.digest_subscriptions;
CREATE TRIGGER digest_subscriptions_insert_audit BEFORE INSERT ON digest.digest_subscriptions
    FOR EACH ROW EXECUTE FUNCTION digest.digest_subscriptions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS digest_subscriptions_update_audit ON digest.digest_subscriptions;
CREATE TRIGGER digest_subscriptions_update_audit BEFORE UPDATE ON digest.digest_subscriptions
    FOR EACH ROW EXECUTE FUNCTION digest.digest_subscriptions_audit_timestamp();

-- ==============================================================================
-- Table: DigestDigestKpi (digest.digest_digest_kpis)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION digest.digest_digest_kpis_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS digest_digest_kpis_insert_audit ON digest.digest_digest_kpis;
CREATE TRIGGER digest_digest_kpis_insert_audit BEFORE INSERT ON digest.digest_digest_kpis
    FOR EACH ROW EXECUTE FUNCTION digest.digest_digest_kpis_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS digest_digest_kpis_update_audit ON digest.digest_digest_kpis;
CREATE TRIGGER digest_digest_kpis_update_audit BEFORE UPDATE ON digest.digest_digest_kpis
    FOR EACH ROW EXECUTE FUNCTION digest.digest_digest_kpis_audit_timestamp();

-- ==============================================================================
-- Table: DigestTip (digest.digest_tips)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION digest.digest_tips_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS digest_tips_insert_audit ON digest.digest_tips;
CREATE TRIGGER digest_tips_insert_audit BEFORE INSERT ON digest.digest_tips
    FOR EACH ROW EXECUTE FUNCTION digest.digest_tips_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS digest_tips_update_audit ON digest.digest_tips;
CREATE TRIGGER digest_tips_update_audit BEFORE UPDATE ON digest.digest_tips
    FOR EACH ROW EXECUTE FUNCTION digest.digest_tips_audit_timestamp();

-- ==============================================================================
-- Table: DigestTipUser (digest.digest_tip_users)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION digest.digest_tip_users_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS digest_tip_users_insert_audit ON digest.digest_tip_users;
CREATE TRIGGER digest_tip_users_insert_audit BEFORE INSERT ON digest.digest_tip_users
    FOR EACH ROW EXECUTE FUNCTION digest.digest_tip_users_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS digest_tip_users_update_audit ON digest.digest_tip_users;
CREATE TRIGGER digest_tip_users_update_audit BEFORE UPDATE ON digest.digest_tip_users
    FOR EACH ROW EXECUTE FUNCTION digest.digest_tip_users_audit_timestamp();

