-- Migration: Create digest_tips table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS digest;

CREATE TABLE IF NOT EXISTS digest.digest_tips (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    sequence INTEGER NOT NULL DEFAULT 1,
    name TEXT NOT NULL,
    tip_description TEXT NOT NULL,
    group_key TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_digest_tips_sequence ON digest.digest_tips (sequence);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_digest_tips_metadata_gin ON digest.digest_tips USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_digest_tips_metadata_deleted_at ON digest.digest_tips ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_digest_tips_metadata_created_at ON digest.digest_tips ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_digest_tips_metadata_updated_at ON digest.digest_tips ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION digest.digest_tips_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS digest_tips_insert_audit ON digest.digest_tips;
CREATE TRIGGER digest_tips_insert_audit BEFORE INSERT ON digest.digest_tips
    FOR EACH ROW EXECUTE FUNCTION digest.digest_tips_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS digest_tips_update_audit ON digest.digest_tips;
CREATE TRIGGER digest_tips_update_audit BEFORE UPDATE ON digest.digest_tips
    FOR EACH ROW EXECUTE FUNCTION digest.digest_tips_audit_timestamp();
