-- Migration: Create digest_digest_kpis table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS digest;

CREATE TABLE IF NOT EXISTS digest.digest_digest_kpis (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    digest_id UUID NOT NULL,
    kpi_key TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_digest_digest_kpis_digest_id_kpi_key ON digest.digest_digest_kpis (digest_id, kpi_key);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_digest_digest_kpis_metadata_gin ON digest.digest_digest_kpis USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_digest_digest_kpis_metadata_deleted_at ON digest.digest_digest_kpis ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_digest_digest_kpis_metadata_created_at ON digest.digest_digest_kpis ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_digest_digest_kpis_metadata_updated_at ON digest.digest_digest_kpis ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION digest.digest_digest_kpis_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS digest_digest_kpis_insert_audit ON digest.digest_digest_kpis;
CREATE TRIGGER digest_digest_kpis_insert_audit BEFORE INSERT ON digest.digest_digest_kpis
    FOR EACH ROW EXECUTE FUNCTION digest.digest_digest_kpis_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS digest_digest_kpis_update_audit ON digest.digest_digest_kpis;
CREATE TRIGGER digest_digest_kpis_update_audit BEFORE UPDATE ON digest.digest_digest_kpis
    FOR EACH ROW EXECUTE FUNCTION digest.digest_digest_kpis_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE digest.digest_digest_kpis ADD CONSTRAINT fk_digest_digest_kpis_digest_id FOREIGN KEY (digest_id) REFERENCES digest.digest_digests (id) ON DELETE CASCADE;
