//! Domain events for DigestDigestKpi entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::DigestDigestKpi;

/// Domain events for DigestDigestKpi — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<DigestDigestKpi>)` variant.
pub type DigestDigestKpiEvent = CrudEvent<DigestDigestKpi>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for DigestDigestKpi events.
pub type DigestDigestKpiEventPublisher = Arc<dyn CrudEventPublisher<DigestDigestKpi> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDigestDigestKpiEventPublisher = NoOpCrudEventPublisher<DigestDigestKpi>;
