//! Domain events for DigestTipUser entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::DigestTipUser;

/// Domain events for DigestTipUser — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<DigestTipUser>)` variant.
pub type DigestTipUserEvent = CrudEvent<DigestTipUser>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for DigestTipUser events.
pub type DigestTipUserEventPublisher = Arc<dyn CrudEventPublisher<DigestTipUser> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDigestTipUserEventPublisher = NoOpCrudEventPublisher<DigestTipUser>;
