//! Event handler trait for DigestTip events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DigestTipEvent;

/// Event handler for DigestTip events.
/// Implement this trait to react to DigestTip lifecycle events.
pub trait DigestTipEventHandler: EventHandler<DigestTipEvent> {}
