//! Event handler trait for DigestSubscription events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DigestSubscriptionEvent;

/// Event handler for DigestSubscription events.
/// Implement this trait to react to DigestSubscription lifecycle events.
pub trait DigestSubscriptionEventHandler: EventHandler<DigestSubscriptionEvent> {}
