//! Event handler trait for DigestDigestKpi events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DigestDigestKpiEvent;

/// Event handler for DigestDigestKpi events.
/// Implement this trait to react to DigestDigestKpi lifecycle events.
pub trait DigestDigestKpiEventHandler: EventHandler<DigestDigestKpiEvent> {}
