//! Domain events for DigestTip entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::DigestTip;

/// Domain events for DigestTip — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<DigestTip>)` variant.
pub type DigestTipEvent = CrudEvent<DigestTip>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for DigestTip events.
pub type DigestTipEventPublisher = Arc<dyn CrudEventPublisher<DigestTip> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDigestTipEventPublisher = NoOpCrudEventPublisher<DigestTip>;
