//! Event handler trait for DigestTipUser events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DigestTipUserEvent;

/// Event handler for DigestTipUser events.
/// Implement this trait to react to DigestTipUser lifecycle events.
pub trait DigestTipUserEventHandler: EventHandler<DigestTipUserEvent> {}
