//! Domain events for DigestSubscription entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::DigestSubscription;

/// Domain events for DigestSubscription — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<DigestSubscription>)` variant.
pub type DigestSubscriptionEvent = CrudEvent<DigestSubscription>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for DigestSubscription events.
pub type DigestSubscriptionEventPublisher = Arc<dyn CrudEventPublisher<DigestSubscription> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDigestSubscriptionEventPublisher = NoOpCrudEventPublisher<DigestSubscription>;
