//! Event handler trait for DigestDigest events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DigestDigestEvent;

/// Event handler for DigestDigest events.
/// Implement this trait to react to DigestDigest lifecycle events.
pub trait DigestDigestEventHandler: EventHandler<DigestDigestEvent> {}
