//! Domain events for DigestDigest entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::DigestDigest;

/// Domain events for DigestDigest — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<DigestDigest>)` variant.
pub type DigestDigestEvent = CrudEvent<DigestDigest>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for DigestDigest events.
pub type DigestDigestEventPublisher = Arc<dyn CrudEventPublisher<DigestDigest> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDigestDigestEventPublisher = NoOpCrudEventPublisher<DigestDigest>;
