//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod digest_digest_events;
pub mod digest_digest_event_handlers;
pub mod digest_subscription_events;
pub mod digest_subscription_event_handlers;
pub mod digest_digest_kpi_events;
pub mod digest_digest_kpi_event_handlers;
pub mod digest_tip_events;
pub mod digest_tip_event_handlers;
pub mod digest_tip_user_events;
pub mod digest_tip_user_event_handlers;

pub use digest_digest_events::{DigestDigestEvent, DigestDigestEventPublisher, NoopDigestDigestEventPublisher};
pub use digest_digest_event_handlers::DigestDigestEventHandler;
pub use digest_subscription_events::{DigestSubscriptionEvent, DigestSubscriptionEventPublisher, NoopDigestSubscriptionEventPublisher};
pub use digest_subscription_event_handlers::DigestSubscriptionEventHandler;
pub use digest_digest_kpi_events::{DigestDigestKpiEvent, DigestDigestKpiEventPublisher, NoopDigestDigestKpiEventPublisher};
pub use digest_digest_kpi_event_handlers::DigestDigestKpiEventHandler;
pub use digest_tip_events::{DigestTipEvent, DigestTipEventPublisher, NoopDigestTipEventPublisher};
pub use digest_tip_event_handlers::DigestTipEventHandler;
pub use digest_tip_user_events::{DigestTipUserEvent, DigestTipUserEventPublisher, NoopDigestTipUserEventPublisher};
pub use digest_tip_user_event_handlers::DigestTipUserEventHandler;

// <<< CUSTOM
// END CUSTOM
