//! DigestDigestKpi seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial DigestDigestKpi data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// DIGESTDIGESTKPI SEEDER
// ============================================================================

/// Seeder for digest_digest_kpi
pub struct SeedDigestDigestKpiSeeder;

impl SeedDigestDigestKpiSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedDigestDigestKpiSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedDigestDigestKpiSeeder {
    fn name(&self) -> &'static str {
        "SeedDigestDigestKpiSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if digest.digest_digest_kpis table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM digest.digest_digest_kpis")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/digest_digest_kpi_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM digest.digest_digest_kpis")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
