//! Repository trait for DigestTip aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the DigestTip aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::DigestTip;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DigestTipPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DigestTipPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DigestTipPaginatedResult {
    pub data: Vec<DigestTip>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DigestTipFilter {
    pub name: Option<String>,
    pub tip_description: Option<String>,
    pub group_key: Option<String>,
}

impl DigestTipFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.tip_description.is_some() || self.group_key.is_some()
    }
}

/// Repository trait for DigestTip aggregate
///
/// This trait defines the persistence contract for DigestTip entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DigestTipRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new digest_tip entity
    async fn save(&self, entity: &DigestTip) -> Result<DigestTip>;

    /// Find digest_tip by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<DigestTip>>;

    /// Find all digest_tip entities
    async fn find_all(&self) -> Result<Vec<DigestTip>>;

    /// Update digest_tip by ID
    async fn update(&self, id: &str, entity: &DigestTip) -> Result<Option<DigestTip>>;

    /// Delete digest_tip by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List digest_tip with pagination
    async fn list(&self, params: DigestTipPaginationParams) -> Result<DigestTipPaginatedResult>;

    /// List digest_tip with pagination and filters
    async fn list_with_filters(&self, params: DigestTipPaginationParams, filters: DigestTipFilter) -> Result<DigestTipPaginatedResult>;

    /// Count all digest_tip entities
    async fn count(&self) -> Result<u64>;

    /// Count digest_tip entities matching filters
    async fn count_with_filters(&self, filters: DigestTipFilter) -> Result<u64>;

    /// Check if digest_tip exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete digest_tip by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted digest_tip by ID
    async fn restore(&self, id: &str) -> Result<Option<DigestTip>>;

    /// List soft-deleted digest_tip entities
    async fn list_deleted(&self, params: DigestTipPaginationParams) -> Result<DigestTipPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save digest_tip entities
    async fn bulk_save(&self, entities: &[DigestTip]) -> Result<Vec<DigestTip>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
