//! Repository trait for DigestDigest aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the DigestDigest aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{DigestDigest, DigestPeriodicity, DigestState};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DigestDigestPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DigestDigestPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DigestDigestPaginatedResult {
    pub data: Vec<DigestDigest>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DigestDigestFilter {
    pub name: Option<String>,
    pub periodicity: Option<DigestPeriodicity>,
    pub state: Option<DigestState>,
    pub company_id: Option<Uuid>,
}

impl DigestDigestFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.periodicity.is_some() || self.state.is_some() || self.company_id.is_some()
    }
}

/// Repository trait for DigestDigest aggregate
///
/// This trait defines the persistence contract for DigestDigest entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DigestDigestRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new digest_digest entity
    async fn save(&self, entity: &DigestDigest) -> Result<DigestDigest>;

    /// Find digest_digest by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<DigestDigest>>;

    /// Find all digest_digest entities
    async fn find_all(&self) -> Result<Vec<DigestDigest>>;

    /// Update digest_digest by ID
    async fn update(&self, id: &str, entity: &DigestDigest) -> Result<Option<DigestDigest>>;

    /// Delete digest_digest by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List digest_digest with pagination
    async fn list(&self, params: DigestDigestPaginationParams) -> Result<DigestDigestPaginatedResult>;

    /// List digest_digest with pagination and filters
    async fn list_with_filters(&self, params: DigestDigestPaginationParams, filters: DigestDigestFilter) -> Result<DigestDigestPaginatedResult>;

    /// Count all digest_digest entities
    async fn count(&self) -> Result<u64>;

    /// Count digest_digest entities matching filters
    async fn count_with_filters(&self, filters: DigestDigestFilter) -> Result<u64>;

    /// Check if digest_digest exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete digest_digest by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted digest_digest by ID
    async fn restore(&self, id: &str) -> Result<Option<DigestDigest>>;

    /// List soft-deleted digest_digest entities
    async fn list_deleted(&self, params: DigestDigestPaginationParams) -> Result<DigestDigestPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save digest_digest entities
    async fn bulk_save(&self, entities: &[DigestDigest]) -> Result<Vec<DigestDigest>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
