//! Repository trait for DigestSubscription aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the DigestSubscription aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{DigestSubscription, DigestSubscriptionState};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DigestSubscriptionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DigestSubscriptionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DigestSubscriptionPaginatedResult {
    pub data: Vec<DigestSubscription>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DigestSubscriptionFilter {
    pub digest_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub state: Option<DigestSubscriptionState>,
}

impl DigestSubscriptionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.digest_id.is_some() || self.user_id.is_some() || self.state.is_some()
    }
}

/// Repository trait for DigestSubscription aggregate
///
/// This trait defines the persistence contract for DigestSubscription entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DigestSubscriptionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new digest_subscription entity
    async fn save(&self, entity: &DigestSubscription) -> Result<DigestSubscription>;

    /// Find digest_subscription by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<DigestSubscription>>;

    /// Find all digest_subscription entities
    async fn find_all(&self) -> Result<Vec<DigestSubscription>>;

    /// Update digest_subscription by ID
    async fn update(&self, id: &str, entity: &DigestSubscription) -> Result<Option<DigestSubscription>>;

    /// Delete digest_subscription by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List digest_subscription with pagination
    async fn list(&self, params: DigestSubscriptionPaginationParams) -> Result<DigestSubscriptionPaginatedResult>;

    /// List digest_subscription with pagination and filters
    async fn list_with_filters(&self, params: DigestSubscriptionPaginationParams, filters: DigestSubscriptionFilter) -> Result<DigestSubscriptionPaginatedResult>;

    /// Count all digest_subscription entities
    async fn count(&self) -> Result<u64>;

    /// Count digest_subscription entities matching filters
    async fn count_with_filters(&self, filters: DigestSubscriptionFilter) -> Result<u64>;

    /// Check if digest_subscription exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete digest_subscription by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted digest_subscription by ID
    async fn restore(&self, id: &str) -> Result<Option<DigestSubscription>>;

    /// List soft-deleted digest_subscription entities
    async fn list_deleted(&self, params: DigestSubscriptionPaginationParams) -> Result<DigestSubscriptionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save digest_subscription entities
    async fn bulk_save(&self, entities: &[DigestSubscription]) -> Result<Vec<DigestSubscription>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
