//! Repository trait for DigestTipUser aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the DigestTipUser aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::DigestTipUser;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DigestTipUserPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DigestTipUserPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DigestTipUserPaginatedResult {
    pub data: Vec<DigestTipUser>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DigestTipUserFilter {
    pub tip_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
}

impl DigestTipUserFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.tip_id.is_some() || self.user_id.is_some()
    }
}

/// Repository trait for DigestTipUser aggregate
///
/// This trait defines the persistence contract for DigestTipUser entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DigestTipUserRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new digest_tip_user entity
    async fn save(&self, entity: &DigestTipUser) -> Result<DigestTipUser>;

    /// Find digest_tip_user by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<DigestTipUser>>;

    /// Find all digest_tip_user entities
    async fn find_all(&self) -> Result<Vec<DigestTipUser>>;

    /// Update digest_tip_user by ID
    async fn update(&self, id: &str, entity: &DigestTipUser) -> Result<Option<DigestTipUser>>;

    /// Delete digest_tip_user by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List digest_tip_user with pagination
    async fn list(&self, params: DigestTipUserPaginationParams) -> Result<DigestTipUserPaginatedResult>;

    /// List digest_tip_user with pagination and filters
    async fn list_with_filters(&self, params: DigestTipUserPaginationParams, filters: DigestTipUserFilter) -> Result<DigestTipUserPaginatedResult>;

    /// Count all digest_tip_user entities
    async fn count(&self) -> Result<u64>;

    /// Count digest_tip_user entities matching filters
    async fn count_with_filters(&self, filters: DigestTipUserFilter) -> Result<u64>;

    /// Check if digest_tip_user exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete digest_tip_user by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted digest_tip_user by ID
    async fn restore(&self, id: &str) -> Result<Option<DigestTipUser>>;

    /// List soft-deleted digest_tip_user entities
    async fn list_deleted(&self, params: DigestTipUserPaginationParams) -> Result<DigestTipUserPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save digest_tip_user entities
    async fn bulk_save(&self, entities: &[DigestTipUser]) -> Result<Vec<DigestTipUser>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
