//! Repository trait for DigestDigestKpi aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the DigestDigestKpi aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::DigestDigestKpi;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DigestDigestKpiPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DigestDigestKpiPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DigestDigestKpiPaginatedResult {
    pub data: Vec<DigestDigestKpi>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DigestDigestKpiFilter {
    pub digest_id: Option<Uuid>,
    pub kpi_key: Option<String>,
}

impl DigestDigestKpiFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.digest_id.is_some() || self.kpi_key.is_some()
    }
}

/// Repository trait for DigestDigestKpi aggregate
///
/// This trait defines the persistence contract for DigestDigestKpi entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DigestDigestKpiRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new digest_digest_kpi entity
    async fn save(&self, entity: &DigestDigestKpi) -> Result<DigestDigestKpi>;

    /// Find digest_digest_kpi by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<DigestDigestKpi>>;

    /// Find all digest_digest_kpi entities
    async fn find_all(&self) -> Result<Vec<DigestDigestKpi>>;

    /// Update digest_digest_kpi by ID
    async fn update(&self, id: &str, entity: &DigestDigestKpi) -> Result<Option<DigestDigestKpi>>;

    /// Delete digest_digest_kpi by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List digest_digest_kpi with pagination
    async fn list(&self, params: DigestDigestKpiPaginationParams) -> Result<DigestDigestKpiPaginatedResult>;

    /// List digest_digest_kpi with pagination and filters
    async fn list_with_filters(&self, params: DigestDigestKpiPaginationParams, filters: DigestDigestKpiFilter) -> Result<DigestDigestKpiPaginatedResult>;

    /// Count all digest_digest_kpi entities
    async fn count(&self) -> Result<u64>;

    /// Count digest_digest_kpi entities matching filters
    async fn count_with_filters(&self, filters: DigestDigestKpiFilter) -> Result<u64>;

    /// Check if digest_digest_kpi exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete digest_digest_kpi by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted digest_digest_kpi by ID
    async fn restore(&self, id: &str) -> Result<Option<DigestDigestKpi>>;

    /// List soft-deleted digest_digest_kpi entities
    async fn list_deleted(&self, params: DigestDigestKpiPaginationParams) -> Result<DigestDigestKpiPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save digest_digest_kpi entities
    async fn bulk_save(&self, entities: &[DigestDigestKpi]) -> Result<Vec<DigestDigestKpi>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
