//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod digest_digest_repository;
pub mod digest_subscription_repository;
pub mod digest_digest_kpi_repository;
pub mod digest_tip_repository;
pub mod digest_tip_user_repository;

// Re-exports
pub use digest_digest_repository::{
    DigestDigestRepository,
    DigestDigestPaginationParams,
    DigestDigestPaginatedResult,
    DigestDigestFilter,
};
pub use digest_subscription_repository::{
    DigestSubscriptionRepository,
    DigestSubscriptionPaginationParams,
    DigestSubscriptionPaginatedResult,
    DigestSubscriptionFilter,
};
pub use digest_digest_kpi_repository::{
    DigestDigestKpiRepository,
    DigestDigestKpiPaginationParams,
    DigestDigestKpiPaginatedResult,
    DigestDigestKpiFilter,
};
pub use digest_tip_repository::{
    DigestTipRepository,
    DigestTipPaginationParams,
    DigestTipPaginatedResult,
    DigestTipFilter,
};
pub use digest_tip_user_repository::{
    DigestTipUserRepository,
    DigestTipUserPaginationParams,
    DigestTipUserPaginatedResult,
    DigestTipUserFilter,
};
