//! Repository for DigestTip entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<DigestTip, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::DigestTip;

/// Table name for DigestTip entities
pub const TABLE_NAME: &str = "digest.digest_tips";

/// Repository for DigestTip entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DigestTipRepository(
    backbone_orm::GenericCrudRepository<DigestTip, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DigestTipRepository {
    type Target = backbone_orm::GenericCrudRepository<DigestTip, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DigestTipRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(DigestTipRepository, DigestTip, soft_delete);
