//! Repository for DigestSubscription entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<DigestSubscription, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::DigestSubscription;

/// Table name for DigestSubscription entities
pub const TABLE_NAME: &str = "digest.digest_subscriptions";

/// Repository for DigestSubscription entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DigestSubscriptionRepository(
    backbone_orm::GenericCrudRepository<DigestSubscription, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DigestSubscriptionRepository {
    type Target = backbone_orm::GenericCrudRepository<DigestSubscription, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DigestSubscriptionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(DigestSubscriptionRepository, DigestSubscription, soft_delete);
