//! Repository for DigestTipUser entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<DigestTipUser, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::DigestTipUser;

/// Table name for DigestTipUser entities
pub const TABLE_NAME: &str = "digest.digest_tip_users";

/// Repository for DigestTipUser entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DigestTipUserRepository(
    backbone_orm::GenericCrudRepository<DigestTipUser, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DigestTipUserRepository {
    type Target = backbone_orm::GenericCrudRepository<DigestTipUser, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DigestTipUserRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(DigestTipUserRepository, DigestTipUser, soft_delete);
