//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod digest_digest_repository;
mod digest_subscription_repository;
mod digest_digest_kpi_repository;
mod digest_tip_repository;
mod digest_tip_user_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use digest_digest_repository::DigestDigestRepository;
pub use digest_subscription_repository::DigestSubscriptionRepository;
pub use digest_digest_kpi_repository::DigestDigestKpiRepository;
pub use digest_tip_repository::DigestTipRepository;
pub use digest_tip_user_repository::DigestTipUserRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
