//! Validator for DigestTipUser entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<DigestTipUser>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::DigestTipUser;

/// Validator type alias for DigestTipUser entities.
pub type DigestTipUserValidator = EntityValidator<DigestTipUser>;

/// Build a validator for DigestTipUser with all schema-defined field rules.
pub fn digest_tip_user_validator() -> DigestTipUserValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
