//! Validator for DigestDigest entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<DigestDigest>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::DigestDigest;

/// Validator type alias for DigestDigest entities.
pub type DigestDigestValidator = EntityValidator<DigestDigest>;

/// Build a validator for DigestDigest with all schema-defined field rules.
pub fn digest_digest_validator() -> DigestDigestValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &DigestDigest| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
