//! Validator for DigestDigestKpi entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<DigestDigestKpi>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::DigestDigestKpi;

/// Validator type alias for DigestDigestKpi entities.
pub type DigestDigestKpiValidator = EntityValidator<DigestDigestKpi>;

/// Build a validator for DigestDigestKpi with all schema-defined field rules.
pub fn digest_digest_kpi_validator() -> DigestDigestKpiValidator {
    EntityValidator::new()
        .rule(RequiredString::new("kpi_key", |e: &DigestDigestKpi| &e.kpi_key))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
