//! Validator for DigestSubscription entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<DigestSubscription>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::DigestSubscription;

/// Validator type alias for DigestSubscription entities.
pub type DigestSubscriptionValidator = EntityValidator<DigestSubscription>;

/// Build a validator for DigestSubscription with all schema-defined field rules.
pub fn digest_subscription_validator() -> DigestSubscriptionValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
