//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod digest_digest_validator;
pub mod digest_subscription_validator;
pub mod digest_digest_kpi_validator;
pub mod digest_tip_validator;
pub mod digest_tip_user_validator;

pub use digest_digest_validator::{DigestDigestValidator, digest_digest_validator};
pub use digest_subscription_validator::{DigestSubscriptionValidator, digest_subscription_validator};
pub use digest_digest_kpi_validator::{DigestDigestKpiValidator, digest_digest_kpi_validator};
pub use digest_tip_validator::{DigestTipValidator, digest_tip_validator};
pub use digest_tip_user_validator::{DigestTipUserValidator, digest_tip_user_validator};

// <<< CUSTOM
// END CUSTOM
