//! Digest Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Digest exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use digest::exports::{DigestDigestDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `DigestDigestDto` - Data transfer object for DigestDigest
/// - `DigestDigestSummary` - Summary view of DigestDigest
/// - `DigestDigestId` - Type-safe ID wrapper
/// - `DigestSubscriptionDto` - Data transfer object for DigestSubscription
/// - `DigestSubscriptionSummary` - Summary view of DigestSubscription
/// - `DigestSubscriptionId` - Type-safe ID wrapper
/// - `DigestDigestKpiDto` - Data transfer object for DigestDigestKpi
/// - `DigestDigestKpiSummary` - Summary view of DigestDigestKpi
/// - `DigestDigestKpiId` - Type-safe ID wrapper
/// - `DigestTipDto` - Data transfer object for DigestTip
/// - `DigestTipSummary` - Summary view of DigestTip
/// - `DigestTipId` - Type-safe ID wrapper
/// - `DigestTipUserDto` - Data transfer object for DigestTipUser
/// - `DigestTipUserSummary` - Summary view of DigestTipUser
/// - `DigestTipUserId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `DigestDigestCreatedEvent` - Published when DigestDigest is created
/// - `DigestDigestUpdatedEvent` - Published when DigestDigest is updated
/// - `DigestDigestDeletedEvent` - Published when DigestDigest is deleted
/// - `DigestSubscriptionCreatedEvent` - Published when DigestSubscription is created
/// - `DigestSubscriptionUpdatedEvent` - Published when DigestSubscription is updated
/// - `DigestSubscriptionDeletedEvent` - Published when DigestSubscription is deleted
/// - `DigestDigestKpiCreatedEvent` - Published when DigestDigestKpi is created
/// - `DigestDigestKpiUpdatedEvent` - Published when DigestDigestKpi is updated
/// - `DigestDigestKpiDeletedEvent` - Published when DigestDigestKpi is deleted
/// - `DigestTipCreatedEvent` - Published when DigestTip is created
/// - `DigestTipUpdatedEvent` - Published when DigestTip is updated
/// - `DigestTipDeletedEvent` - Published when DigestTip is deleted
/// - `DigestTipUserCreatedEvent` - Published when DigestTipUser is created
/// - `DigestTipUserUpdatedEvent` - Published when DigestTipUser is updated
/// - `DigestTipUserDeletedEvent` - Published when DigestTipUser is deleted
pub struct ExportSummary;
